'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Copy, Check, Download, Code, FileJson, Globe, Palette, FileText } from 'lucide-react'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import type { CanvasForm, FormField } from '@/types/form'

interface ExportModalProps {
  form: CanvasForm | null
  isOpen: boolean
  onClose: () => void
  formData?: Record<string, any>  // Optional filled form data
}

type ExportTab = 'pdf' | 'wordpress' | 'html' | 'react' | 'json'

const WORDPRESS_PLUGINS = [
  { id: 'gravity', name: 'Gravity Forms', icon: '🔷' },
  { id: 'wpforms', name: 'WPForms', icon: '🟠' },
  { id: 'contact7', name: 'Contact Form 7', icon: '🔵' },
  { id: 'ninja', name: 'Ninja Forms', icon: '🟣' },
  { id: 'formidable', name: 'Formidable Forms', icon: '🟢' },
] as const

const WP_BUILDERS = [
  { id: 'elementor', name: 'Elementor' },
  { id: 'bricks', name: 'Bricks Builder' },
  { id: 'gutenberg', name: 'Gutenberg' },
  { id: 'divi', name: 'Divi' },
  { id: 'beaver', name: 'Beaver Builder' },
] as const

export function ExportModal({ form, isOpen, onClose, formData = {} }: ExportModalProps) {
  const [activeTab, setActiveTab] = useState<ExportTab>('pdf')
  const [wpPlugin, setWpPlugin] = useState<string>('gravity')
  const [wpBuilder, setWpBuilder] = useState<string>('elementor')
  const [copied, setCopied] = useState(false)
  const [includeStyles, setIncludeStyles] = useState(true)
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false)
  const [localFormData, setLocalFormData] = useState<Record<string, any>>(formData)

  if (!form) return null

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = (content: string, filename: string, type = 'text/plain') => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  const handlePdfExport = async () => {
    if (!form) return
    setIsGeneratingPdf(true)
    
    try {
      const pdfDoc = await PDFDocument.create()
      const page = pdfDoc.addPage([595.28, 841.89]) // A4
      const { width, height } = page.getSize()
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
      
      let yPos = height - 60
      const margin = 50
      const lineHeight = 20
      const fieldGap = 30

      // Title
      page.drawText(form.name, { x: margin, y: yPos, size: 24, font: boldFont, color: rgb(0.1, 0.1, 0.1) })
      yPos -= 35

      // Description
      if (form.description) {
        page.drawText(form.description, { x: margin, y: yPos, size: 11, font, color: rgb(0.4, 0.4, 0.4) })
        yPos -= 30
      }

      // Separator line
      page.drawLine({ start: { x: margin, y: yPos }, end: { x: width - margin, y: yPos }, thickness: 1, color: rgb(0.8, 0.8, 0.8) })
      yPos -= 25

      // Fields
      for (const field of form.fields) {
        if (field.type === 'divider' || field.type === 'heading' || field.type === 'paragraph') continue
        
        // Check if we need a new page
        if (yPos < 100) {
          const newPage = pdfDoc.addPage([595.28, 841.89])
          yPos = height - 60
        }

        // Field label
        const label = `${field.label}${field.required ? ' *' : ''}:`
        page.drawText(label, { x: margin, y: yPos, size: 11, font: boldFont, color: rgb(0.2, 0.2, 0.2) })
        yPos -= lineHeight

        // Field value
        const value = localFormData[field.id] || formData[field.id] || field.defaultValue || '___________________'
        const displayValue = Array.isArray(value) ? value.join(', ') : String(value)
        
        // Draw value with box
        page.drawRectangle({ x: margin, y: yPos - 5, width: width - margin * 2, height: 22, borderColor: rgb(0.8, 0.8, 0.8), borderWidth: 1, color: rgb(0.98, 0.98, 0.98) })
        page.drawText(displayValue, { x: margin + 8, y: yPos + 2, size: 11, font, color: rgb(0.1, 0.1, 0.1), maxWidth: width - margin * 2 - 16 })
        
        yPos -= fieldGap
      }

      // Footer
      const footerY = 40
      page.drawText(`Generated by RevoForms • ${new Date().toLocaleDateString()}`, { x: margin, y: footerY, size: 9, font, color: rgb(0.6, 0.6, 0.6) })

      const pdfBytes = await pdfDoc.save()
      const buffer = Buffer.from(pdfBytes)
      const blob = new Blob([buffer], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${form.name.toLowerCase().replace(/\s+/g, '-')}.pdf`
      a.click()
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('PDF generation error:', error)
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setIsGeneratingPdf(false)
    }
  }

  const getExportCode = (): string => {
    switch (activeTab) {
      case 'wordpress': return generateWordPressCode(form, wpPlugin, wpBuilder, includeStyles)
      case 'html': return generateHTMLCode(form, includeStyles)
      case 'react': return generateReactCode(form, includeStyles)
      case 'json': return JSON.stringify(form, null, 2)
      default: return ''
    }
  }

  const getFilename = (): string => {
    const base = form.name.toLowerCase().replace(/\s+/g, '-')
    switch (activeTab) {
      case 'wordpress': return `${base}-${wpPlugin}.php`
      case 'html': return `${base}.html`
      case 'react': return `${base}.tsx`
      case 'json': return `${base}.json`
      default: return `${base}.txt`
    }
  }

  const code = activeTab !== 'pdf' ? getExportCode() : ''

  const handleFieldValueChange = (fieldId: string, value: string) => {
    setLocalFormData(prev => ({ ...prev, [fieldId]: value }))
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm" onClick={onClose}>
          <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
            className="w-full max-w-4xl max-h-[90vh] bg-[#0f0f1a] border border-white/10 rounded-2xl overflow-hidden flex flex-col"
            onClick={e => e.stopPropagation()}>
            
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
              <div>
                <h2 className="text-lg font-semibold text-white">Export: {form.name}</h2>
                <p className="text-sm text-white/50">Choose format and download your form</p>
              </div>
              <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-lg transition-colors">
                <X className="w-5 h-5 text-white/70" />
              </button>
            </div>

            {/* Tabs */}
            <div className="flex border-b border-white/10 overflow-x-auto">
              {[
                { id: 'pdf', label: 'PDF', icon: FileText },
                { id: 'wordpress', label: 'WordPress', icon: Globe },
                { id: 'html', label: 'HTML/CSS', icon: Code },
                { id: 'react', label: 'React', icon: Palette },
                { id: 'json', label: 'JSON', icon: FileJson },
              ].map(({ id, label, icon: Icon }) => (
                <button key={id} onClick={() => setActiveTab(id as ExportTab)}
                  className={`flex items-center gap-2 px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap ${
                    activeTab === id ? 'text-neon-cyan border-b-2 border-neon-cyan bg-neon-cyan/5' : 'text-white/60 hover:text-white hover:bg-white/5'
                  }`}>
                  <Icon className="w-4 h-4" />{label}
                </button>
              ))}
            </div>

            {/* Content */}
            <div className="flex-1 overflow-auto p-6">
              {activeTab === 'pdf' && (
                <div className="space-y-4">
                  <div className="p-4 bg-white/5 border border-white/10 rounded-xl">
                    <h3 className="text-sm font-medium text-white mb-3">Fill form data before export (optional)</h3>
                    <div className="space-y-3 max-h-[300px] overflow-y-auto">
                      {form.fields.filter(f => !['divider', 'heading', 'paragraph'].includes(f.type)).map(field => (
                        <div key={field.id}>
                          <label className="block text-xs text-white/60 mb-1">{field.label}</label>
                          <input type="text" value={localFormData[field.id] || formData[field.id] || field.defaultValue || ''}
                            onChange={(e) => handleFieldValueChange(field.id, e.target.value)}
                            placeholder={field.placeholder || `Enter ${field.label.toLowerCase()}`}
                            className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white text-sm focus:border-neon-cyan/50 focus:outline-none" />
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <button onClick={handlePdfExport} disabled={isGeneratingPdf}
                    className="w-full py-3 bg-gradient-to-r from-neon-cyan to-neon-purple text-white font-medium rounded-xl hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center justify-center gap-2">
                    {isGeneratingPdf ? <span className="animate-spin">⏳</span> : <Download className="w-5 h-5" />}
                    {isGeneratingPdf ? 'Generating PDF...' : 'Download PDF'}
                  </button>
                </div>
              )}

              {activeTab === 'wordpress' && (
                <div className="space-y-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-white/80 mb-2">Form Plugin</label>
                    <div className="flex flex-wrap gap-2">
                      {WORDPRESS_PLUGINS.map(plugin => (
                        <button key={plugin.id} onClick={() => setWpPlugin(plugin.id)}
                          className={`px-4 py-2 rounded-lg text-sm transition-colors ${wpPlugin === plugin.id ? 'bg-neon-cyan/20 text-neon-cyan border border-neon-cyan/50' : 'bg-white/5 text-white/70 border border-white/10 hover:bg-white/10'}`}>
                          {plugin.icon} {plugin.name}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-white/80 mb-2">Page Builder</label>
                    <div className="flex flex-wrap gap-2">
                      {WP_BUILDERS.map(builder => (
                        <button key={builder.id} onClick={() => setWpBuilder(builder.id)}
                          className={`px-4 py-2 rounded-lg text-sm transition-colors ${wpBuilder === builder.id ? 'bg-neon-purple/20 text-neon-purple border border-neon-purple/50' : 'bg-white/5 text-white/70 border border-white/10 hover:bg-white/10'}`}>
                          {builder.name}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {activeTab !== 'pdf' && (
                <>
                  <div className="flex items-center gap-4 mb-4">
                    <label className="flex items-center gap-2 text-sm text-white/70">
                      <input type="checkbox" checked={includeStyles} onChange={(e) => setIncludeStyles(e.target.checked)} className="w-4 h-4 rounded accent-neon-cyan" />
                      Include styles
                    </label>
                  </div>
                  <div className="relative">
                    <pre className="bg-black/50 border border-white/10 rounded-xl p-4 overflow-auto max-h-[400px] text-sm text-white/80 font-mono">
                      <code>{code}</code>
                    </pre>
                  </div>
                </>
              )}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-between px-6 py-4 border-t border-white/10 bg-black/20">
              <p className="text-xs text-white/40">
                {activeTab === 'pdf' && 'Export form as fillable PDF document'}
                {activeTab === 'wordpress' && `Ready for ${WORDPRESS_PLUGINS.find(p => p.id === wpPlugin)?.name} + ${WP_BUILDERS.find(b => b.id === wpBuilder)?.name}`}
                {activeTab === 'html' && 'Standalone HTML with embedded CSS'}
                {activeTab === 'react' && 'React component with Tailwind CSS'}
                {activeTab === 'json' && 'Raw form data structure'}
              </p>
              {activeTab !== 'pdf' && (
                <div className="flex gap-3">
                  <button onClick={() => handleCopy(code)}
                    className="flex items-center gap-2 px-4 py-2 bg-white/10 text-white rounded-lg hover:bg-white/20 transition-colors">
                    {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button onClick={() => handleDownload(code, getFilename())}
                    className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-neon-cyan to-neon-purple text-white rounded-lg hover:opacity-90 transition-opacity">
                    <Download className="w-4 h-4" />Download
                  </button>
                </div>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}


// ============================================
// EXPORT GENERATORS
// ============================================

function getFieldTypeForWP(type: string, plugin: string): string {
  const mappings: Record<string, Record<string, string>> = {
    gravity: { text: 'text', email: 'email', phone: 'phone', number: 'number', textarea: 'textarea', select: 'select', radio: 'radio', checkbox: 'checkbox', date: 'date', time: 'time', file: 'fileupload', url: 'website' },
    wpforms: { text: 'text', email: 'email', phone: 'phone', number: 'number', textarea: 'textarea', select: 'select', radio: 'radio', checkbox: 'checkbox', date: 'date', time: 'time', file: 'file-upload', url: 'url' },
    contact7: { text: 'text', email: 'email', phone: 'tel', number: 'number', textarea: 'textarea', select: 'select', radio: 'radio', checkbox: 'checkbox', date: 'date', file: 'file', url: 'url' },
    ninja: { text: 'textbox', email: 'email', phone: 'phone', number: 'number', textarea: 'textarea', select: 'listselect', radio: 'listradio', checkbox: 'listcheckbox', date: 'date', time: 'time', file: 'file_upload', url: 'textbox' },
  }
  return mappings[plugin]?.[type] || 'text'
}

function generateWordPressCode(form: CanvasForm, plugin: string, builder: string, includeStyles: boolean): string {
  const colors = form.styling?.colors || { primary: '#6366f1', background: '#ffffff', text: '#1e293b', border: '#e2e8f0' }
  const formSlug = form.name.toLowerCase().replace(/\s+/g, '_')
  
  return `<?php
/**
 * ${form.name}
 * Generated by RevoForms for ${plugin.charAt(0).toUpperCase() + plugin.slice(1)} + ${builder.charAt(0).toUpperCase() + builder.slice(1)}
 */

// Shortcode: [revoform_${form.id.slice(0, 8)}]
add_shortcode('revoform_${form.id.slice(0, 8)}', 'render_revoform_${formSlug}');

function render_revoform_${formSlug}() {
    ob_start();
    ?>
    <form class="revoform" method="post">
        ${form.fields.map(f => `<div class="form-field">
            <label>${f.label}${f.required ? ' *' : ''}</label>
            ${f.type === 'textarea' 
              ? `<textarea name="${f.id}" placeholder="${f.placeholder || ''}"${f.required ? ' required' : ''}></textarea>`
              : f.type === 'select'
              ? `<select name="${f.id}"${f.required ? ' required' : ''}><option value="">${f.placeholder || 'Select...'}</option>${(f.options || []).map(o => `<option value="${typeof o === 'string' ? o : o.value}">${typeof o === 'string' ? o : o.label}</option>`).join('')}</select>`
              : `<input type="${f.type}" name="${f.id}" placeholder="${f.placeholder || ''}"${f.required ? ' required' : ''} />`
            }
        </div>`).join('\n        ')}
        <button type="submit">${form.settings.submitButtonText}</button>
    </form>
    <?php
    return ob_get_clean();
}

${includeStyles ? `
add_action('wp_head', 'revoform_${formSlug}_styles');
function revoform_${formSlug}_styles() { ?>
<style>
.revoform { max-width: 500px; padding: 24px; background: ${colors.background}; border-radius: 16px; }
.revoform .form-field { margin-bottom: 16px; }
.revoform label { display: block; font-weight: 500; margin-bottom: 6px; color: ${colors.text}; }
.revoform input, .revoform textarea, .revoform select { width: 100%; padding: 12px; border: 1px solid ${colors.border}; border-radius: 8px; }
.revoform button { width: 100%; padding: 14px; background: ${colors.primary}; color: white; border: none; border-radius: 8px; cursor: pointer; }
</style>
<?php }` : ''}
`
}

function generateHTMLCode(form: CanvasForm, includeStyles: boolean): string {
  const colors = form.styling?.colors || { primary: '#6366f1', secondary: '#8b5cf6', background: '#ffffff', surface: '#f8fafc', text: '#1e293b', border: '#e2e8f0' }
  const borderRadius = form.styling?.borderRadius || { input: '12px', button: '12px', form: '16px' }

  const styles = includeStyles ? `
  <style>
    .revoform { max-width: 500px; margin: 0 auto; padding: 32px; background: ${colors.background}; border-radius: ${borderRadius.form}; font-family: system-ui, sans-serif; }
    .revoform h2 { color: ${colors.text}; margin-bottom: 8px; }
    .revoform .field { margin-bottom: 20px; }
    .revoform label { display: block; color: ${colors.text}; font-weight: 500; margin-bottom: 6px; font-size: 14px; }
    .revoform .required { color: #ef4444; }
    .revoform input, .revoform textarea, .revoform select { width: 100%; padding: 12px 16px; background: ${colors.surface}; border: 1px solid ${colors.border}; border-radius: ${borderRadius.input}; color: ${colors.text}; font-size: 16px; box-sizing: border-box; }
    .revoform input:focus, .revoform textarea:focus { outline: none; border-color: ${colors.primary}; }
    .revoform button { width: 100%; padding: 14px 24px; background: linear-gradient(135deg, ${colors.primary}, ${colors.secondary}); color: white; border: none; border-radius: ${borderRadius.button}; font-size: 16px; font-weight: 600; cursor: pointer; }
    .revoform button:hover { opacity: 0.9; }
  </style>` : ''

  let fieldsHTML = form.fields.map(field => {
    const required = field.required ? '<span class="required">*</span>' : ''
    if (field.type === 'textarea') return `<div class="field"><label>${field.label} ${required}</label><textarea name="${field.id}" placeholder="${field.placeholder || ''}" rows="4"${field.required ? ' required' : ''}></textarea></div>`
    if (field.type === 'select') return `<div class="field"><label>${field.label} ${required}</label><select name="${field.id}"${field.required ? ' required' : ''}><option value="">${field.placeholder || 'Select...'}</option>${(field.options || []).map(o => `<option value="${typeof o === 'string' ? o : o.value}">${typeof o === 'string' ? o : o.label}</option>`).join('')}</select></div>`
    return `<div class="field"><label>${field.label} ${required}</label><input type="${field.type}" name="${field.id}" placeholder="${field.placeholder || ''}"${field.required ? ' required' : ''} /></div>`
  }).join('\n    ')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${form.name}</title>${styles}
</head>
<body>
  <form class="revoform" id="${form.id}">
    <h2>${form.name}</h2>
    ${form.description ? `<p style="color: #64748b; margin-bottom: 24px;">${form.description}</p>` : ''}
    ${fieldsHTML}
    <button type="submit">${form.settings.submitButtonText}</button>
  </form>
  <script>
    document.getElementById('${form.id}').onsubmit = function(e) {
      e.preventDefault();
      alert('${form.settings.successMessage}');
    };
  </script>
</body>
</html>`
}

function generateReactCode(form: CanvasForm, includeStyles: boolean): string {
  const colors = form.styling?.colors || { primary: '#6366f1', secondary: '#8b5cf6' }
  
  const fieldComponents = form.fields.map(field => {
    if (field.type === 'textarea') return `      <div className="mb-5"><label className="block text-sm font-medium mb-2">${field.label}${field.required ? ' <span className="text-red-500">*</span>' : ''}</label><textarea name="${field.id}" placeholder="${field.placeholder || ''}" rows={4}${field.required ? ' required' : ''} className="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-primary" /></div>`
    if (field.type === 'select') return `      <div className="mb-5"><label className="block text-sm font-medium mb-2">${field.label}${field.required ? ' <span className="text-red-500">*</span>' : ''}</label><select name="${field.id}"${field.required ? ' required' : ''} className="w-full px-4 py-3 border rounded-xl"><option value="">${field.placeholder || 'Select...'}</option>${(field.options || []).map(o => `<option value="${typeof o === 'string' ? o : o.value}">${typeof o === 'string' ? o : o.label}</option>`).join('')}</select></div>`
    return `      <div className="mb-5"><label className="block text-sm font-medium mb-2">${field.label}${field.required ? ' <span className="text-red-500">*</span>' : ''}</label><input type="${field.type}" name="${field.id}" placeholder="${field.placeholder || ''}"${field.required ? ' required' : ''} className="w-full px-4 py-3 border rounded-xl focus:ring-2 focus:ring-primary" /></div>`
  }).join('\n\n')

  return `'use client'

import { useState, FormEvent } from 'react'

export default function ${form.name.replace(/\s+/g, '')}Form() {
  const [submitted, setSubmitted] = useState(false)

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setSubmitted(true)
  }

  if (submitted) return (
    <div className="max-w-md mx-auto p-8 text-center">
      <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-green-100 flex items-center justify-center">
        <svg className="w-8 h-8 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
      </div>
      <h3 className="text-xl font-bold mb-2">Success!</h3>
      <p className="text-gray-600">${form.settings.successMessage}</p>
      <button onClick={() => setSubmitted(false)} className="mt-4 px-6 py-2 bg-primary text-white rounded-xl">Submit Another</button>
    </div>
  )

  return (
    <form onSubmit={handleSubmit} className="max-w-md mx-auto p-8 rounded-2xl" style={{ background: '${colors.background || '#fff'}' }}>
      <h2 className="text-2xl font-bold mb-2">${form.name}</h2>
      ${form.description ? `<p className="text-gray-600 mb-6">${form.description}</p>` : ''}
      
${fieldComponents}

      <button type="submit" className="w-full py-3 text-white font-semibold rounded-xl transition-opacity hover:opacity-90" style={{ background: 'linear-gradient(135deg, ${colors.primary}, ${colors.secondary})' }}>
        ${form.settings.submitButtonText}
      </button>
    </form>
  )
}`
}
